export const conversations = [
    {
        type:"received",
        date:"07-07-2022",
        from:["Ahmed Said"],
        to:["Ashraf Ezzat","Muhammad Basha","Mahmoud el Nemr","Hesham El Syed",],
        cc:["Secertary","sherif","Hossam"],
        title:"Daily Report 25-07-2022",
        conversation:"2022 LinkedIn Ireland Unlimited Company, Wilton Plaza, Wilton Place, Dublin 2 LinkedIn is a registered business name of LinkedIn Ireland Unlimited Company. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.2022 LinkedIn Ireland Unlimited Company, Wilton Plaza, Wilton Place, Dublin 2 LinkedIn is a registered business name of LinkedIn Ireland Unlimited Company. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.2022 LinkedIn Ireland Unlimited",
        time:"10:05 AM",
        reading:true,
        attch:true,
    },
    {
        type:"received",
        date:"08-07-2022",
        from:["Jory"],
        to:["Ashraf Ezzat","Muhammad Basha","Mahmoud el Nemr","Hesham El Syed",],
        cc:["Secertary","sherif","Hossam"],
        title:"Daily Report 25-07-2022",
        conversation:"2022 LinkedIn Ireland Unlimited Company, Wilton Plaza, Wilton Place, Dublin 2 LinkedIn is a registered business name of LinkedIn Ireland Unlimited Company. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.2022 LinkedIn Ireland Unlimited Company, Wilton Plaza, Wilton Place, Dublin 2 LinkedIn is a registered business name of LinkedIn Ireland Unlimited Company. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.2022 LinkedIn Ireland Unlimited",
        time:"10:05 AM",
        reading:true,
        attch:true,
    },
    {
        type:"received",
        date:"09-07-2022",
        from:["Tamim Said"],
        to:["Ashraf Ezzat","Muhammad Basha","Mahmoud el Nemr","Hesham El Syed",],
        cc:["Secertary","sherif","Hossam"],
        title:"Daily Report 25-07-2022",
        conversation:"2022 LinkedIn Ireland Unlimited Company, Wilton Plaza, Wilton Place, Dublin 2 LinkedIn is a registered business name of LinkedIn Ireland Unlimited Company. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.2022 LinkedIn Ireland Unlimited Company, Wilton Plaza, Wilton Place, Dublin 2 LinkedIn is a registered business name of LinkedIn Ireland Unlimited Company. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.2022 LinkedIn Ireland Unlimited",
        time:"10:05 AM",
        reading:true,
        attch:true,
    },
    {
        type:"received",
        date:"10-07-2022",
        from:["Basma Ahmed"],
        to:["Ashraf Ezzat","Muhammad Basha","Mahmoud el Nemr","Hesham El Syed",],
        cc:["Secertary","sherif","Hossam"],
        title:"Daily Report 25-07-2022",
        conversation:"2022 LinkedIn Ireland Unlimited Company, Wilton Plaza, Wilton Place, Dublin 2 LinkedIn is a registered business name of LinkedIn Ireland Unlimited Company. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.2022 LinkedIn Ireland Unlimited Company, Wilton Plaza, Wilton Place, Dublin 2 LinkedIn is a registered business name of LinkedIn Ireland Unlimited Company. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.2022 LinkedIn Ireland Unlimited",
        time:"10:05 AM",
        reading:true,
        attch:true,
    },
    {
        type:"sended",
        date:"10-07-2022",
        from:["Basma Ahmed"],
        to:["Ahmed Said"],
        cc:[],
        title:"Lovly Message",
        conversation:"2022 LinkedIn Ireland Unlimited Company, Wilton Plaza, Wilton Place, Dublin 2 LinkedIn is a registered business name of LinkedIn Ireland Unlimited Company. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.2022 LinkedIn Ireland Unlimited Company, Wilton Plaza, Wilton Place, Dublin 2 LinkedIn is a registered business name of LinkedIn Ireland Unlimited Company. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.2022 LinkedIn Ireland Unlimited",
        time:"10:05 AM",
        reading:true,
        attch:true,
    },
    {
        type:"deleted",
        date:"10-07-2022",
        from:["Ahmed Said"],
        to:["Ali Boby"],
        cc:[],
        title:"Unknown Message",
        conversation:"2022 LinkedIn Ireland Unlimited Company, Wilton Plaza, Wilton Place, Dublin 2 LinkedIn is a registered business name of LinkedIn Ireland Unlimited Company. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.2022 LinkedIn Ireland Unlimited Company, Wilton Plaza, Wilton Place, Dublin 2 LinkedIn is a registered business name of LinkedIn Ireland Unlimited Company. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.2022 LinkedIn Ireland Unlimited",
        time:"11:15 AM",
        reading:true,
        attch:true,
    },
]